version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-Route-Planning-Project:/CppND-Route-Planning-Project
      - ../route_model:/CppND-Route-Planning-Project/src
      - ../scripts/build-test.sh:/build-test.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    # command: >
    #   bash -c "
    #   apt-get install -y x11-apps &&
    #   export DISPLAY=host.docker.internal:0 &&
    #   xeyes
    #   "
    command: >
      bash -c "
      chmod +x /build-test.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /build-test.sh
      "
