version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-System-Monitor-Project-Updated:/CppND-System-Monitor-Project-Updated
      - ../system_monitor/src:/CppND-System-Monitor-Project-Updated/src
      - ../system_monitor/include:/CppND-System-Monitor-Project-Updated/include
      - ../scripts/build-project.justcompile.sh:/build-project.justcompile.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: >
      bash -c "
      chmod +x /build-project.justcompile.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /build-project.justcompile.sh
      "
