version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-Route-Planning-Project:/CppND-Route-Planning-Project
      - ../route_model:/CppND-Route-Planning-Project/src
      - ../scripts/build-project.sh:/build-project.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: >
      bash -c "
      chmod +x /build-project.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /build-project.sh
      "
